# .readthedocs.yaml

version: 2

build:
  os: "ubuntu-22.04"  # Set the OS to a supported Ubuntu version
  tools:
    python: "3.9"  # Python version to use
  commands:
    # Install Chromium
    - apt-get update
    - apt-get install -y chromium-browser
    
sphinx:
  configuration: source/conf.py  # Path to your Sphinx config file

python:
  install:
    - method: pip
      path: .
    - requirements: source/requirements.txt  # Path to your requirements file