comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
      paths:
        - "./src/"
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
      paths:
        - "./src/"
