comment: false

coverage:
  status:
    project:
      default:
        target: 99%
        threshold: 1%
        informational: true
        paths:
          - "src/*"

ignore:
  - "tests/*"
          
